/**
 * Builds every brand asset from its source, the same way each time:
 *
 *   npm run brand:export
 *
 * - Wordmark SVGs are outlined from the real Archivo font, so they
 *   look right without the font installed.
 * - PNGs are rendered from the HTML templates in brand-assets/templates
 *   with headless Chromium at an exact size — never screenshotted by hand.
 * - The files the site itself uses are copied into app/ and public/brand/,
 *   including one share image per tool page (public/brand/og/<slug>.png).
 *
 * Token graphics follow lib/config/site.ts: none are made when the token is
 * disabled, and the one graphic that carries a mint address is only made
 * once the token is live with a real mint. No placeholder address is ever
 * rendered into an image.
 */
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { register } from "node:module";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { chromium } from "@playwright/test";
import opentype from "opentype.js";
import { TOKEN_CONFIG } from "../../lib/config/site.ts";

// The tool pages are data in the site's own TypeScript, which uses the "@/" alias; the loader teaches Node to follow it.
register("./alias-loader.mjs", import.meta.url);
const { TOOLS } = await import("../../lib/tools/definitions.ts");

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const brand = path.join(root, "brand-assets");
const templates = path.join(brand, "templates");
const exportsDir = path.join(brand, "exports");
const publicBrand = path.join(root, "public/brand");

const COBALT = "#3563e9";
const CORNERS = "M9 15V9h6M23 17v6h-6";
const corners = (extra = "") =>
  `<path d="${CORNERS}" fill="none" stroke="#fff" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"${extra}/>`;

/** The mark as a rounded tile (favicons, app icons) or filling the whole square (icons the platform masks itself). */
function markSvg({ bleed = false, inset = 1 } = {}) {
  const transform = inset === 1 ? "" : ` transform="translate(16 16) scale(${inset}) translate(-16 -16)"`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32"${bleed ? "" : ' rx="7"'} fill="${COBALT}"/>${corners(transform)}</svg>`;
}

// Same test as isSolanaAddress in lib/token.ts.
const mintIsReal = /^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(TOKEN_CONFIG.mintAddress);
const tokenLive = TOKEN_CONFIG.enabled && TOKEN_CONFIG.status === "live" && mintIsReal;

async function buildWordmarks() {
  const woff = await readFile(path.join(root, "node_modules/@fontsource/archivo/files/archivo-latin-600-normal.woff"));
  const font = opentype.parse(woff.buffer.slice(woff.byteOffset, woff.byteOffset + woff.byteLength));
  const size = 23;
  const capHeight = (font.tables.os2.sCapHeight / font.unitsPerEm) * size;
  // Cap height centred on the 32-unit tile; the text starts one tile-third after it.
  const baseline = 16 + capHeight / 2;
  // Set glyph by glyph: opentype.js cannot run every substitution feature this font carries, and the name needs none of them.
  const text = new opentype.Path();
  const unit = size / font.unitsPerEm;
  const glyphs = [..."JustResize"].map((character) => font.charToGlyph(character));
  let x = 42;
  glyphs.forEach((glyph, index) => {
    text.extend(glyph.getPath(x, baseline, size));
    const kerning = index + 1 < glyphs.length ? font.getKerningValue(glyph, glyphs[index + 1]) : 0;
    x += (glyph.advanceWidth + kerning) * unit + size * -0.01;
  });
  const width = Math.ceil(text.getBoundingBox().x2 + 1);

  const wordmark = (fill, note) =>
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} 32" role="img" aria-label="JustResize">\n` +
    `  <!-- ${note} Generated by scripts/brand/export.mjs; the letters are outlines of Archivo SemiBold. -->\n` +
    `  <rect width="32" height="32" rx="7" fill="${COBALT}"/>\n  ${corners()}\n` +
    `  <path d="${text.toPathData(2)}" fill="${fill}"/>\n</svg>\n`;

  await writeFile(path.join(brand, "justresize-wordmark-dark.svg"), wordmark("#ececef", "For dark backgrounds."));
  await writeFile(path.join(brand, "justresize-wordmark-light.svg"), wordmark("#15161a", "For light backgrounds."));
}

/** PNG entries in an ICO container: every current browser reads them, and it keeps the favicon crisp at each size. */
function ico(images) {
  const header = Buffer.alloc(6 + images.length * 16);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(images.length, 4);
  let offset = header.length;
  images.forEach(({ size, data }, index) => {
    const entry = 6 + index * 16;
    header.writeUInt8(size === 256 ? 0 : size, entry);
    header.writeUInt8(size === 256 ? 0 : size, entry + 1);
    header.writeUInt16LE(1, entry + 4);
    header.writeUInt16LE(32, entry + 6);
    header.writeUInt32LE(data.length, entry + 8);
    header.writeUInt32LE(offset, entry + 12);
    offset += data.length;
  });
  return Buffer.concat([header, ...images.map((image) => image.data)]);
}

await mkdir(path.join(exportsDir, "x-headers"), { recursive: true });
await mkdir(path.join(exportsDir, "og"), { recursive: true });
await mkdir(path.join(publicBrand, "og"), { recursive: true });
await buildWordmarks();

const browser = await chromium.launch();

async function renderTemplate({ template, out, width, height, scale = 1, fill }) {
  const context = await browser.newContext({ viewport: { width, height }, deviceScaleFactor: scale });
  const page = await context.newPage();
  await page.goto(pathToFileURL(path.join(templates, template)).href);
  if (fill) {
    await page.evaluate((values) => {
      for (const [key, value] of Object.entries(values)) {
        for (const element of document.querySelectorAll(`[data-token="${key}"]`)) element.textContent = value;
      }
    }, fill);
  }
  // Fonts load lazily, so ask for each face by name: a template then renders the same whether or not the font was already in use.
  const fontsLoaded = await page.evaluate(async () => {
    const faces = ['400 20px "Archivo"', '500 20px "Archivo"', '600 20px "Archivo"'];
    const loaded = await Promise.all(faces.map((face) => document.fonts.load(face)));
    await document.fonts.ready;
    return loaded.every((result) => result.length > 0);
  });
  if (!fontsLoaded) throw new Error(`${template}: the brand fonts did not load. Run npm install first.`);
  await page.screenshot({ path: path.join(exportsDir, out), clip: { x: 0, y: 0, width, height } });
  await context.close();
  console.log(`  ${out}`);
}

async function renderIcon(svg, size) {
  const context = await browser.newContext({ viewport: { width: size, height: size } });
  const page = await context.newPage();
  await page.setContent(`<style>html,body{margin:0;background:transparent}svg{display:block;width:${size}px;height:${size}px}</style>${svg}`);
  const data = await page.screenshot({ omitBackground: true, clip: { x: 0, y: 0, width: size, height: size } });
  await context.close();
  return data;
}

async function writeIcon(svg, size, out) {
  await writeFile(path.join(exportsDir, out), await renderIcon(svg, size));
  console.log(`  ${out}`);
}

console.log("Brand assets → brand-assets/exports");

// The homepage hero's second line, as the site words it for the token's state (app/page.tsx). Empty when it has nothing to say.
const heroTokenLine = !TOKEN_CONFIG.enabled
  ? ""
  : tokenLive
    ? `Token live on ${TOKEN_CONFIG.network}.`
    : TOKEN_CONFIG.status === "prelaunch" || TOKEN_CONFIG.status === "live"
      ? `Token launching on ${TOKEN_CONFIG.network}.`
      : "";

/** Alternative X headers to choose between: different copy, ground and scale. Each is rendered at 1× and 2× into exports/x-headers/. */
const X_HEADER_VARIANTS = ["quiet-dark", "quiet-cobalt", "quiet-paper", "measure", "squeeze", "tiles"];

const jobs = [
  { template: "avatar.html", out: "justresize-avatar-1024.png", width: 1024, height: 1024 },
  { template: "avatar.html", out: "justresize-avatar-400.png", width: 1024, height: 1024, scale: 400 / 1024 },
  { template: "x-header.html", out: "justresize-x-header.png", width: 1500, height: 500, fill: { line: heroTokenLine } },
  { template: "x-header.html", out: "justresize-x-header@2x.png", width: 1500, height: 500, scale: 2, fill: { line: heroTokenLine } },
  // The same header again beside the alternatives, so the whole choice is in one folder.
  { template: "x-header.html", out: "x-headers/justresize-x-header-hero.png", width: 1500, height: 500, fill: { line: heroTokenLine } },
  { template: "x-header.html", out: "x-headers/justresize-x-header-hero@2x.png", width: 1500, height: 500, scale: 2, fill: { line: heroTokenLine } },
  ...X_HEADER_VARIANTS.flatMap((variant) => [
    { template: `x-header-${variant}.html`, out: `x-headers/justresize-x-header-${variant}.png`, width: 1500, height: 500 },
    { template: `x-header-${variant}.html`, out: `x-headers/justresize-x-header-${variant}@2x.png`, width: 1500, height: 500, scale: 2 },
  ]),
  { template: "og.html", out: "justresize-og.png", width: 1200, height: 630 },
  { template: "post-product-launch.html", out: "justresize-post-product-launch.png", width: 1600, height: 900 },
  { template: "post-target-file-size.html", out: "justresize-post-target-file-size.png", width: 1600, height: 900 },
  { template: "post-local-processing.html", out: "justresize-post-local-processing.png", width: 1600, height: 900 },
  { template: "post-batch-resize.html", out: "justresize-post-batch-resize.png", width: 1600, height: 900 },
];

// One share image per tool page, from that page's own heading and description.
for (const tool of TOOLS) {
  jobs.push({
    template: "og-tool.html",
    out: `og/${tool.slug}.png`,
    width: 1200,
    height: 630,
    fill: { heading: tool.heading, description: tool.description, url: `justresize.com/${tool.slug}` },
  });
}

if (TOKEN_CONFIG.enabled) {
  jobs.push(
    { template: "token-avatar.html", out: "justresize-token-avatar-1024.png", width: 1024, height: 1024 },
    { template: "token-avatar.html", out: "justresize-token-avatar-400.png", width: 1024, height: 1024, scale: 400 / 1024 },
    { template: "x-header-token.html", out: "justresize-x-header-token.png", width: 1500, height: 500 },
    { template: "x-header-token.html", out: "justresize-x-header-token@2x.png", width: 1500, height: 500, scale: 2 },
    { template: "token-og.html", out: "justresize-token-og.png", width: 1200, height: 630 },
  );
}

if (tokenLive) {
  const ticker = TOKEN_CONFIG.ticker.replace(/^\$+/, "");
  jobs.push({
    template: "post-token-launch.html",
    out: "justresize-post-token-launch.png",
    width: 1600,
    height: 900,
    fill: { mint: TOKEN_CONFIG.mintAddress, ticker: ticker ? `($${ticker})` : "" },
  });
}

for (const job of jobs) await renderTemplate(job);

await writeIcon(markSvg(), 192, "justresize-icon-192.png");
await writeIcon(markSvg(), 512, "justresize-icon-512.png");
// Maskable: the platform crops to its own shape, so the tile fills the square and the mark stays in the central 80%.
await writeIcon(markSvg({ bleed: true, inset: 0.8 }), 512, "justresize-icon-maskable-512.png");
// iOS rounds the corners itself and shows black behind transparency, so this one is a full square too.
await writeIcon(markSvg({ bleed: true }), 180, "justresize-apple-touch-icon.png");
const faviconSizes = [16, 32, 48];
const favicons = [];
for (const size of faviconSizes) favicons.push({ size, data: await renderIcon(markSvg(), size) });
await writeFile(path.join(exportsDir, "favicon.ico"), ico(favicons));
console.log("  favicon.ico");

await browser.close();

if (!tokenLive) {
  console.log("  (justresize-post-token-launch.png skipped: the token is not live with a real mint in lib/config/site.ts)");
}

// What the site serves. Everything else stays in brand-assets/ for social profiles and posts.
const publish = [
  [path.join(brand, "justresize-mark.svg"), path.join(publicBrand, "justresize-mark.svg")],
  [path.join(brand, "justresize-wordmark-dark.svg"), path.join(publicBrand, "justresize-wordmark-dark.svg")],
  [path.join(brand, "justresize-wordmark-light.svg"), path.join(publicBrand, "justresize-wordmark-light.svg")],
  [path.join(exportsDir, "justresize-og.png"), path.join(publicBrand, "justresize-og.png")],
  [path.join(exportsDir, "justresize-icon-192.png"), path.join(publicBrand, "justresize-icon-192.png")],
  [path.join(exportsDir, "justresize-icon-512.png"), path.join(publicBrand, "justresize-icon-512.png")],
  [path.join(exportsDir, "justresize-icon-maskable-512.png"), path.join(publicBrand, "justresize-icon-maskable-512.png")],
  [path.join(exportsDir, "justresize-apple-touch-icon.png"), path.join(root, "app/apple-icon.png")],
  [path.join(exportsDir, "favicon.ico"), path.join(root, "app/favicon.ico")],
];
for (const tool of TOOLS) publish.push([path.join(exportsDir, "og", `${tool.slug}.png`), path.join(publicBrand, "og", `${tool.slug}.png`)]);
if (TOKEN_CONFIG.enabled) {
  publish.push([path.join(exportsDir, "justresize-token-og.png"), path.join(publicBrand, "justresize-token-og.png")]);
}
for (const [from, to] of publish) await copyFile(from, to);
console.log("Site assets → public/brand, app/favicon.ico, app/apple-icon.png");
